### ISSUE TITLE
Using PackageLoader with mod_wsgi and virtualenv

### ISSUE THREAD

**Issue by BradMclain** [mitsuhiko/jinja2#509]
So not really sure if this is the right place for this but here goes.

So I am attempting to load some templates from our project with the package installed in a virtualenv using the PackageLoader and it works fine on OSX El Capitan running a werkzeug development server.

Extract from `MANIFEST.in`
```
include project/templates/html/*
```

The loading code
```
env = Environment(loader=PackageLoader('project', 'templates/html'))
template = env.get_template("%s.html" % template_name)
```

When I deploy the code to run on the production server (Ubuntu 14.04 server) using apache2 and mod_wsgi I get TemplateNotFound exceptions whenever I attempt to load any templates.

Apache excerpt
```
WSGIPythonHome  /srv/project/venv
```

Anyone have any idea on what might be going wrong? Have I missed something?

**Comment by BradMclain** [comment]
Solved: was missing `include_package_data=True` in the setup.py this was working when installed locally but not once packaged and moved to another machine.

Sorry to trouble you.

**Comment by Raveline** [comment]
I'm sorry to anser to this more than one year later, but I also got fooled by this (I had no package_data in my setup.py). It might be a good idea to add a line or two about the fact that package setup must be able to include the templates in the documentation on PackageLoader, since it's quite easy to forget.
